/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.broadinstitute.gatk.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GenotypeRow extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3743918606402796601L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GenotypeRow\",\"namespace\":\"org.broadinstitute.gatk.avro\",\"fields\":[{\"name\":\"position\",\"type\":[\"null\",\"long\"]},{\"name\":\"sample\",\"type\":[\"null\",\"string\"]},{\"name\":\"state\",\"type\":[\"null\",\"string\"]},{\"name\":\"ref\",\"type\":[\"null\",\"string\"]},{\"name\":\"alt\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_RAW_MQ\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_RAW_MQRankSum\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_QUALapprox\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_RAW_ReadPosRankSum\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_SB_TABLE\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_VarDP\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_GT\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_AD\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_DP\",\"type\":[\"null\",\"long\"]},{\"name\":\"call_GQ\",\"type\":[\"null\",\"long\"]},{\"name\":\"call_PGT\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_PID\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_PL\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GenotypeRow> ENCODER =
      new BinaryMessageEncoder<GenotypeRow>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GenotypeRow> DECODER =
      new BinaryMessageDecoder<GenotypeRow>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GenotypeRow> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GenotypeRow> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GenotypeRow> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GenotypeRow>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GenotypeRow to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GenotypeRow from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GenotypeRow instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GenotypeRow fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long position;
   private java.lang.CharSequence sample;
   private java.lang.CharSequence state;
   private java.lang.CharSequence ref;
   private java.lang.CharSequence alt;
   private java.lang.CharSequence AS_RAW_MQ;
   private java.lang.CharSequence AS_RAW_MQRankSum;
   private java.lang.CharSequence AS_QUALapprox;
   private java.lang.CharSequence AS_RAW_ReadPosRankSum;
   private java.lang.CharSequence AS_SB_TABLE;
   private java.lang.CharSequence AS_VarDP;
   private java.lang.CharSequence call_GT;
   private java.lang.CharSequence call_AD;
   private java.lang.Long call_DP;
   private java.lang.Long call_GQ;
   private java.lang.CharSequence call_PGT;
   private java.lang.CharSequence call_PID;
   private java.lang.CharSequence call_PL;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GenotypeRow() {}

  /**
   * All-args constructor.
   * @param position The new value for position
   * @param sample The new value for sample
   * @param state The new value for state
   * @param ref The new value for ref
   * @param alt The new value for alt
   * @param AS_RAW_MQ The new value for AS_RAW_MQ
   * @param AS_RAW_MQRankSum The new value for AS_RAW_MQRankSum
   * @param AS_QUALapprox The new value for AS_QUALapprox
   * @param AS_RAW_ReadPosRankSum The new value for AS_RAW_ReadPosRankSum
   * @param AS_SB_TABLE The new value for AS_SB_TABLE
   * @param AS_VarDP The new value for AS_VarDP
   * @param call_GT The new value for call_GT
   * @param call_AD The new value for call_AD
   * @param call_DP The new value for call_DP
   * @param call_GQ The new value for call_GQ
   * @param call_PGT The new value for call_PGT
   * @param call_PID The new value for call_PID
   * @param call_PL The new value for call_PL
   */
  public GenotypeRow(java.lang.Long position, java.lang.CharSequence sample, java.lang.CharSequence state, java.lang.CharSequence ref, java.lang.CharSequence alt, java.lang.CharSequence AS_RAW_MQ, java.lang.CharSequence AS_RAW_MQRankSum, java.lang.CharSequence AS_QUALapprox, java.lang.CharSequence AS_RAW_ReadPosRankSum, java.lang.CharSequence AS_SB_TABLE, java.lang.CharSequence AS_VarDP, java.lang.CharSequence call_GT, java.lang.CharSequence call_AD, java.lang.Long call_DP, java.lang.Long call_GQ, java.lang.CharSequence call_PGT, java.lang.CharSequence call_PID, java.lang.CharSequence call_PL) {
    this.position = position;
    this.sample = sample;
    this.state = state;
    this.ref = ref;
    this.alt = alt;
    this.AS_RAW_MQ = AS_RAW_MQ;
    this.AS_RAW_MQRankSum = AS_RAW_MQRankSum;
    this.AS_QUALapprox = AS_QUALapprox;
    this.AS_RAW_ReadPosRankSum = AS_RAW_ReadPosRankSum;
    this.AS_SB_TABLE = AS_SB_TABLE;
    this.AS_VarDP = AS_VarDP;
    this.call_GT = call_GT;
    this.call_AD = call_AD;
    this.call_DP = call_DP;
    this.call_GQ = call_GQ;
    this.call_PGT = call_PGT;
    this.call_PID = call_PID;
    this.call_PL = call_PL;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return position;
    case 1: return sample;
    case 2: return state;
    case 3: return ref;
    case 4: return alt;
    case 5: return AS_RAW_MQ;
    case 6: return AS_RAW_MQRankSum;
    case 7: return AS_QUALapprox;
    case 8: return AS_RAW_ReadPosRankSum;
    case 9: return AS_SB_TABLE;
    case 10: return AS_VarDP;
    case 11: return call_GT;
    case 12: return call_AD;
    case 13: return call_DP;
    case 14: return call_GQ;
    case 15: return call_PGT;
    case 16: return call_PID;
    case 17: return call_PL;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: position = (java.lang.Long)value$; break;
    case 1: sample = (java.lang.CharSequence)value$; break;
    case 2: state = (java.lang.CharSequence)value$; break;
    case 3: ref = (java.lang.CharSequence)value$; break;
    case 4: alt = (java.lang.CharSequence)value$; break;
    case 5: AS_RAW_MQ = (java.lang.CharSequence)value$; break;
    case 6: AS_RAW_MQRankSum = (java.lang.CharSequence)value$; break;
    case 7: AS_QUALapprox = (java.lang.CharSequence)value$; break;
    case 8: AS_RAW_ReadPosRankSum = (java.lang.CharSequence)value$; break;
    case 9: AS_SB_TABLE = (java.lang.CharSequence)value$; break;
    case 10: AS_VarDP = (java.lang.CharSequence)value$; break;
    case 11: call_GT = (java.lang.CharSequence)value$; break;
    case 12: call_AD = (java.lang.CharSequence)value$; break;
    case 13: call_DP = (java.lang.Long)value$; break;
    case 14: call_GQ = (java.lang.Long)value$; break;
    case 15: call_PGT = (java.lang.CharSequence)value$; break;
    case 16: call_PID = (java.lang.CharSequence)value$; break;
    case 17: call_PL = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'position' field.
   * @return The value of the 'position' field.
   */
  public java.lang.Long getPosition() {
    return position;
  }


  /**
   * Sets the value of the 'position' field.
   * @param value the value to set.
   */
  public void setPosition(java.lang.Long value) {
    this.position = value;
  }

  /**
   * Gets the value of the 'sample' field.
   * @return The value of the 'sample' field.
   */
  public java.lang.CharSequence getSample() {
    return sample;
  }


  /**
   * Sets the value of the 'sample' field.
   * @param value the value to set.
   */
  public void setSample(java.lang.CharSequence value) {
    this.sample = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'ref' field.
   * @return The value of the 'ref' field.
   */
  public java.lang.CharSequence getRef() {
    return ref;
  }


  /**
   * Sets the value of the 'ref' field.
   * @param value the value to set.
   */
  public void setRef(java.lang.CharSequence value) {
    this.ref = value;
  }

  /**
   * Gets the value of the 'alt' field.
   * @return The value of the 'alt' field.
   */
  public java.lang.CharSequence getAlt() {
    return alt;
  }


  /**
   * Sets the value of the 'alt' field.
   * @param value the value to set.
   */
  public void setAlt(java.lang.CharSequence value) {
    this.alt = value;
  }

  /**
   * Gets the value of the 'AS_RAW_MQ' field.
   * @return The value of the 'AS_RAW_MQ' field.
   */
  public java.lang.CharSequence getASRAWMQ() {
    return AS_RAW_MQ;
  }


  /**
   * Sets the value of the 'AS_RAW_MQ' field.
   * @param value the value to set.
   */
  public void setASRAWMQ(java.lang.CharSequence value) {
    this.AS_RAW_MQ = value;
  }

  /**
   * Gets the value of the 'AS_RAW_MQRankSum' field.
   * @return The value of the 'AS_RAW_MQRankSum' field.
   */
  public java.lang.CharSequence getASRAWMQRankSum() {
    return AS_RAW_MQRankSum;
  }


  /**
   * Sets the value of the 'AS_RAW_MQRankSum' field.
   * @param value the value to set.
   */
  public void setASRAWMQRankSum(java.lang.CharSequence value) {
    this.AS_RAW_MQRankSum = value;
  }

  /**
   * Gets the value of the 'AS_QUALapprox' field.
   * @return The value of the 'AS_QUALapprox' field.
   */
  public java.lang.CharSequence getASQUALapprox() {
    return AS_QUALapprox;
  }


  /**
   * Sets the value of the 'AS_QUALapprox' field.
   * @param value the value to set.
   */
  public void setASQUALapprox(java.lang.CharSequence value) {
    this.AS_QUALapprox = value;
  }

  /**
   * Gets the value of the 'AS_RAW_ReadPosRankSum' field.
   * @return The value of the 'AS_RAW_ReadPosRankSum' field.
   */
  public java.lang.CharSequence getASRAWReadPosRankSum() {
    return AS_RAW_ReadPosRankSum;
  }


  /**
   * Sets the value of the 'AS_RAW_ReadPosRankSum' field.
   * @param value the value to set.
   */
  public void setASRAWReadPosRankSum(java.lang.CharSequence value) {
    this.AS_RAW_ReadPosRankSum = value;
  }

  /**
   * Gets the value of the 'AS_SB_TABLE' field.
   * @return The value of the 'AS_SB_TABLE' field.
   */
  public java.lang.CharSequence getASSBTABLE() {
    return AS_SB_TABLE;
  }


  /**
   * Sets the value of the 'AS_SB_TABLE' field.
   * @param value the value to set.
   */
  public void setASSBTABLE(java.lang.CharSequence value) {
    this.AS_SB_TABLE = value;
  }

  /**
   * Gets the value of the 'AS_VarDP' field.
   * @return The value of the 'AS_VarDP' field.
   */
  public java.lang.CharSequence getASVarDP() {
    return AS_VarDP;
  }


  /**
   * Sets the value of the 'AS_VarDP' field.
   * @param value the value to set.
   */
  public void setASVarDP(java.lang.CharSequence value) {
    this.AS_VarDP = value;
  }

  /**
   * Gets the value of the 'call_GT' field.
   * @return The value of the 'call_GT' field.
   */
  public java.lang.CharSequence getCallGT() {
    return call_GT;
  }


  /**
   * Sets the value of the 'call_GT' field.
   * @param value the value to set.
   */
  public void setCallGT(java.lang.CharSequence value) {
    this.call_GT = value;
  }

  /**
   * Gets the value of the 'call_AD' field.
   * @return The value of the 'call_AD' field.
   */
  public java.lang.CharSequence getCallAD() {
    return call_AD;
  }


  /**
   * Sets the value of the 'call_AD' field.
   * @param value the value to set.
   */
  public void setCallAD(java.lang.CharSequence value) {
    this.call_AD = value;
  }

  /**
   * Gets the value of the 'call_DP' field.
   * @return The value of the 'call_DP' field.
   */
  public java.lang.Long getCallDP() {
    return call_DP;
  }


  /**
   * Sets the value of the 'call_DP' field.
   * @param value the value to set.
   */
  public void setCallDP(java.lang.Long value) {
    this.call_DP = value;
  }

  /**
   * Gets the value of the 'call_GQ' field.
   * @return The value of the 'call_GQ' field.
   */
  public java.lang.Long getCallGQ() {
    return call_GQ;
  }


  /**
   * Sets the value of the 'call_GQ' field.
   * @param value the value to set.
   */
  public void setCallGQ(java.lang.Long value) {
    this.call_GQ = value;
  }

  /**
   * Gets the value of the 'call_PGT' field.
   * @return The value of the 'call_PGT' field.
   */
  public java.lang.CharSequence getCallPGT() {
    return call_PGT;
  }


  /**
   * Sets the value of the 'call_PGT' field.
   * @param value the value to set.
   */
  public void setCallPGT(java.lang.CharSequence value) {
    this.call_PGT = value;
  }

  /**
   * Gets the value of the 'call_PID' field.
   * @return The value of the 'call_PID' field.
   */
  public java.lang.CharSequence getCallPID() {
    return call_PID;
  }


  /**
   * Sets the value of the 'call_PID' field.
   * @param value the value to set.
   */
  public void setCallPID(java.lang.CharSequence value) {
    this.call_PID = value;
  }

  /**
   * Gets the value of the 'call_PL' field.
   * @return The value of the 'call_PL' field.
   */
  public java.lang.CharSequence getCallPL() {
    return call_PL;
  }


  /**
   * Sets the value of the 'call_PL' field.
   * @param value the value to set.
   */
  public void setCallPL(java.lang.CharSequence value) {
    this.call_PL = value;
  }

  /**
   * Creates a new GenotypeRow RecordBuilder.
   * @return A new GenotypeRow RecordBuilder
   */
  public static org.broadinstitute.gatk.avro.GenotypeRow.Builder newBuilder() {
    return new org.broadinstitute.gatk.avro.GenotypeRow.Builder();
  }

  /**
   * Creates a new GenotypeRow RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GenotypeRow RecordBuilder
   */
  public static org.broadinstitute.gatk.avro.GenotypeRow.Builder newBuilder(org.broadinstitute.gatk.avro.GenotypeRow.Builder other) {
    if (other == null) {
      return new org.broadinstitute.gatk.avro.GenotypeRow.Builder();
    } else {
      return new org.broadinstitute.gatk.avro.GenotypeRow.Builder(other);
    }
  }

  /**
   * Creates a new GenotypeRow RecordBuilder by copying an existing GenotypeRow instance.
   * @param other The existing instance to copy.
   * @return A new GenotypeRow RecordBuilder
   */
  public static org.broadinstitute.gatk.avro.GenotypeRow.Builder newBuilder(org.broadinstitute.gatk.avro.GenotypeRow other) {
    if (other == null) {
      return new org.broadinstitute.gatk.avro.GenotypeRow.Builder();
    } else {
      return new org.broadinstitute.gatk.avro.GenotypeRow.Builder(other);
    }
  }

  /**
   * RecordBuilder for GenotypeRow instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GenotypeRow>
    implements org.apache.avro.data.RecordBuilder<GenotypeRow> {

    private java.lang.Long position;
    private java.lang.CharSequence sample;
    private java.lang.CharSequence state;
    private java.lang.CharSequence ref;
    private java.lang.CharSequence alt;
    private java.lang.CharSequence AS_RAW_MQ;
    private java.lang.CharSequence AS_RAW_MQRankSum;
    private java.lang.CharSequence AS_QUALapprox;
    private java.lang.CharSequence AS_RAW_ReadPosRankSum;
    private java.lang.CharSequence AS_SB_TABLE;
    private java.lang.CharSequence AS_VarDP;
    private java.lang.CharSequence call_GT;
    private java.lang.CharSequence call_AD;
    private java.lang.Long call_DP;
    private java.lang.Long call_GQ;
    private java.lang.CharSequence call_PGT;
    private java.lang.CharSequence call_PID;
    private java.lang.CharSequence call_PL;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.broadinstitute.gatk.avro.GenotypeRow.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.position)) {
        this.position = data().deepCopy(fields()[0].schema(), other.position);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sample)) {
        this.sample = data().deepCopy(fields()[1].schema(), other.sample);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ref)) {
        this.ref = data().deepCopy(fields()[3].schema(), other.ref);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.alt)) {
        this.alt = data().deepCopy(fields()[4].schema(), other.alt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.AS_RAW_MQ)) {
        this.AS_RAW_MQ = data().deepCopy(fields()[5].schema(), other.AS_RAW_MQ);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.AS_RAW_MQRankSum)) {
        this.AS_RAW_MQRankSum = data().deepCopy(fields()[6].schema(), other.AS_RAW_MQRankSum);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.AS_QUALapprox)) {
        this.AS_QUALapprox = data().deepCopy(fields()[7].schema(), other.AS_QUALapprox);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.AS_RAW_ReadPosRankSum)) {
        this.AS_RAW_ReadPosRankSum = data().deepCopy(fields()[8].schema(), other.AS_RAW_ReadPosRankSum);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.AS_SB_TABLE)) {
        this.AS_SB_TABLE = data().deepCopy(fields()[9].schema(), other.AS_SB_TABLE);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.AS_VarDP)) {
        this.AS_VarDP = data().deepCopy(fields()[10].schema(), other.AS_VarDP);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.call_GT)) {
        this.call_GT = data().deepCopy(fields()[11].schema(), other.call_GT);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.call_AD)) {
        this.call_AD = data().deepCopy(fields()[12].schema(), other.call_AD);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.call_DP)) {
        this.call_DP = data().deepCopy(fields()[13].schema(), other.call_DP);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.call_GQ)) {
        this.call_GQ = data().deepCopy(fields()[14].schema(), other.call_GQ);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.call_PGT)) {
        this.call_PGT = data().deepCopy(fields()[15].schema(), other.call_PGT);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.call_PID)) {
        this.call_PID = data().deepCopy(fields()[16].schema(), other.call_PID);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.call_PL)) {
        this.call_PL = data().deepCopy(fields()[17].schema(), other.call_PL);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
    }

    /**
     * Creates a Builder by copying an existing GenotypeRow instance
     * @param other The existing instance to copy.
     */
    private Builder(org.broadinstitute.gatk.avro.GenotypeRow other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.position)) {
        this.position = data().deepCopy(fields()[0].schema(), other.position);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sample)) {
        this.sample = data().deepCopy(fields()[1].schema(), other.sample);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ref)) {
        this.ref = data().deepCopy(fields()[3].schema(), other.ref);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.alt)) {
        this.alt = data().deepCopy(fields()[4].schema(), other.alt);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.AS_RAW_MQ)) {
        this.AS_RAW_MQ = data().deepCopy(fields()[5].schema(), other.AS_RAW_MQ);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.AS_RAW_MQRankSum)) {
        this.AS_RAW_MQRankSum = data().deepCopy(fields()[6].schema(), other.AS_RAW_MQRankSum);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.AS_QUALapprox)) {
        this.AS_QUALapprox = data().deepCopy(fields()[7].schema(), other.AS_QUALapprox);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.AS_RAW_ReadPosRankSum)) {
        this.AS_RAW_ReadPosRankSum = data().deepCopy(fields()[8].schema(), other.AS_RAW_ReadPosRankSum);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.AS_SB_TABLE)) {
        this.AS_SB_TABLE = data().deepCopy(fields()[9].schema(), other.AS_SB_TABLE);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.AS_VarDP)) {
        this.AS_VarDP = data().deepCopy(fields()[10].schema(), other.AS_VarDP);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.call_GT)) {
        this.call_GT = data().deepCopy(fields()[11].schema(), other.call_GT);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.call_AD)) {
        this.call_AD = data().deepCopy(fields()[12].schema(), other.call_AD);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.call_DP)) {
        this.call_DP = data().deepCopy(fields()[13].schema(), other.call_DP);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.call_GQ)) {
        this.call_GQ = data().deepCopy(fields()[14].schema(), other.call_GQ);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.call_PGT)) {
        this.call_PGT = data().deepCopy(fields()[15].schema(), other.call_PGT);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.call_PID)) {
        this.call_PID = data().deepCopy(fields()[16].schema(), other.call_PID);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.call_PL)) {
        this.call_PL = data().deepCopy(fields()[17].schema(), other.call_PL);
        fieldSetFlags()[17] = true;
      }
    }

    /**
      * Gets the value of the 'position' field.
      * @return The value.
      */
    public java.lang.Long getPosition() {
      return position;
    }


    /**
      * Sets the value of the 'position' field.
      * @param value The value of 'position'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setPosition(java.lang.Long value) {
      validate(fields()[0], value);
      this.position = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'position' field has been set.
      * @return True if the 'position' field has been set, false otherwise.
      */
    public boolean hasPosition() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'position' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearPosition() {
      position = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sample' field.
      * @return The value.
      */
    public java.lang.CharSequence getSample() {
      return sample;
    }


    /**
      * Sets the value of the 'sample' field.
      * @param value The value of 'sample'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setSample(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.sample = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sample' field has been set.
      * @return True if the 'sample' field has been set, false otherwise.
      */
    public boolean hasSample() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sample' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearSample() {
      sample = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setState(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearState() {
      state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ref' field.
      * @return The value.
      */
    public java.lang.CharSequence getRef() {
      return ref;
    }


    /**
      * Sets the value of the 'ref' field.
      * @param value The value of 'ref'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setRef(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ref = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ref' field has been set.
      * @return True if the 'ref' field has been set, false otherwise.
      */
    public boolean hasRef() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ref' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearRef() {
      ref = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'alt' field.
      * @return The value.
      */
    public java.lang.CharSequence getAlt() {
      return alt;
    }


    /**
      * Sets the value of the 'alt' field.
      * @param value The value of 'alt'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setAlt(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.alt = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'alt' field has been set.
      * @return True if the 'alt' field has been set, false otherwise.
      */
    public boolean hasAlt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'alt' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearAlt() {
      alt = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'AS_RAW_MQ' field.
      * @return The value.
      */
    public java.lang.CharSequence getASRAWMQ() {
      return AS_RAW_MQ;
    }


    /**
      * Sets the value of the 'AS_RAW_MQ' field.
      * @param value The value of 'AS_RAW_MQ'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setASRAWMQ(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.AS_RAW_MQ = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'AS_RAW_MQ' field has been set.
      * @return True if the 'AS_RAW_MQ' field has been set, false otherwise.
      */
    public boolean hasASRAWMQ() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'AS_RAW_MQ' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearASRAWMQ() {
      AS_RAW_MQ = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'AS_RAW_MQRankSum' field.
      * @return The value.
      */
    public java.lang.CharSequence getASRAWMQRankSum() {
      return AS_RAW_MQRankSum;
    }


    /**
      * Sets the value of the 'AS_RAW_MQRankSum' field.
      * @param value The value of 'AS_RAW_MQRankSum'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setASRAWMQRankSum(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.AS_RAW_MQRankSum = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'AS_RAW_MQRankSum' field has been set.
      * @return True if the 'AS_RAW_MQRankSum' field has been set, false otherwise.
      */
    public boolean hasASRAWMQRankSum() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'AS_RAW_MQRankSum' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearASRAWMQRankSum() {
      AS_RAW_MQRankSum = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'AS_QUALapprox' field.
      * @return The value.
      */
    public java.lang.CharSequence getASQUALapprox() {
      return AS_QUALapprox;
    }


    /**
      * Sets the value of the 'AS_QUALapprox' field.
      * @param value The value of 'AS_QUALapprox'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setASQUALapprox(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.AS_QUALapprox = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'AS_QUALapprox' field has been set.
      * @return True if the 'AS_QUALapprox' field has been set, false otherwise.
      */
    public boolean hasASQUALapprox() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'AS_QUALapprox' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearASQUALapprox() {
      AS_QUALapprox = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'AS_RAW_ReadPosRankSum' field.
      * @return The value.
      */
    public java.lang.CharSequence getASRAWReadPosRankSum() {
      return AS_RAW_ReadPosRankSum;
    }


    /**
      * Sets the value of the 'AS_RAW_ReadPosRankSum' field.
      * @param value The value of 'AS_RAW_ReadPosRankSum'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setASRAWReadPosRankSum(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.AS_RAW_ReadPosRankSum = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'AS_RAW_ReadPosRankSum' field has been set.
      * @return True if the 'AS_RAW_ReadPosRankSum' field has been set, false otherwise.
      */
    public boolean hasASRAWReadPosRankSum() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'AS_RAW_ReadPosRankSum' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearASRAWReadPosRankSum() {
      AS_RAW_ReadPosRankSum = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'AS_SB_TABLE' field.
      * @return The value.
      */
    public java.lang.CharSequence getASSBTABLE() {
      return AS_SB_TABLE;
    }


    /**
      * Sets the value of the 'AS_SB_TABLE' field.
      * @param value The value of 'AS_SB_TABLE'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setASSBTABLE(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.AS_SB_TABLE = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'AS_SB_TABLE' field has been set.
      * @return True if the 'AS_SB_TABLE' field has been set, false otherwise.
      */
    public boolean hasASSBTABLE() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'AS_SB_TABLE' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearASSBTABLE() {
      AS_SB_TABLE = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'AS_VarDP' field.
      * @return The value.
      */
    public java.lang.CharSequence getASVarDP() {
      return AS_VarDP;
    }


    /**
      * Sets the value of the 'AS_VarDP' field.
      * @param value The value of 'AS_VarDP'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setASVarDP(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.AS_VarDP = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'AS_VarDP' field has been set.
      * @return True if the 'AS_VarDP' field has been set, false otherwise.
      */
    public boolean hasASVarDP() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'AS_VarDP' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearASVarDP() {
      AS_VarDP = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'call_GT' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallGT() {
      return call_GT;
    }


    /**
      * Sets the value of the 'call_GT' field.
      * @param value The value of 'call_GT'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setCallGT(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.call_GT = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'call_GT' field has been set.
      * @return True if the 'call_GT' field has been set, false otherwise.
      */
    public boolean hasCallGT() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'call_GT' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearCallGT() {
      call_GT = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'call_AD' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallAD() {
      return call_AD;
    }


    /**
      * Sets the value of the 'call_AD' field.
      * @param value The value of 'call_AD'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setCallAD(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.call_AD = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'call_AD' field has been set.
      * @return True if the 'call_AD' field has been set, false otherwise.
      */
    public boolean hasCallAD() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'call_AD' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearCallAD() {
      call_AD = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'call_DP' field.
      * @return The value.
      */
    public java.lang.Long getCallDP() {
      return call_DP;
    }


    /**
      * Sets the value of the 'call_DP' field.
      * @param value The value of 'call_DP'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setCallDP(java.lang.Long value) {
      validate(fields()[13], value);
      this.call_DP = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'call_DP' field has been set.
      * @return True if the 'call_DP' field has been set, false otherwise.
      */
    public boolean hasCallDP() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'call_DP' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearCallDP() {
      call_DP = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'call_GQ' field.
      * @return The value.
      */
    public java.lang.Long getCallGQ() {
      return call_GQ;
    }


    /**
      * Sets the value of the 'call_GQ' field.
      * @param value The value of 'call_GQ'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setCallGQ(java.lang.Long value) {
      validate(fields()[14], value);
      this.call_GQ = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'call_GQ' field has been set.
      * @return True if the 'call_GQ' field has been set, false otherwise.
      */
    public boolean hasCallGQ() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'call_GQ' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearCallGQ() {
      call_GQ = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'call_PGT' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallPGT() {
      return call_PGT;
    }


    /**
      * Sets the value of the 'call_PGT' field.
      * @param value The value of 'call_PGT'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setCallPGT(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.call_PGT = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'call_PGT' field has been set.
      * @return True if the 'call_PGT' field has been set, false otherwise.
      */
    public boolean hasCallPGT() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'call_PGT' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearCallPGT() {
      call_PGT = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'call_PID' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallPID() {
      return call_PID;
    }


    /**
      * Sets the value of the 'call_PID' field.
      * @param value The value of 'call_PID'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setCallPID(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.call_PID = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'call_PID' field has been set.
      * @return True if the 'call_PID' field has been set, false otherwise.
      */
    public boolean hasCallPID() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'call_PID' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearCallPID() {
      call_PID = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'call_PL' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallPL() {
      return call_PL;
    }


    /**
      * Sets the value of the 'call_PL' field.
      * @param value The value of 'call_PL'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder setCallPL(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.call_PL = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'call_PL' field has been set.
      * @return True if the 'call_PL' field has been set, false otherwise.
      */
    public boolean hasCallPL() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'call_PL' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.GenotypeRow.Builder clearCallPL() {
      call_PL = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GenotypeRow build() {
      try {
        GenotypeRow record = new GenotypeRow();
        record.position = fieldSetFlags()[0] ? this.position : (java.lang.Long) defaultValue(fields()[0]);
        record.sample = fieldSetFlags()[1] ? this.sample : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.state = fieldSetFlags()[2] ? this.state : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ref = fieldSetFlags()[3] ? this.ref : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.alt = fieldSetFlags()[4] ? this.alt : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.AS_RAW_MQ = fieldSetFlags()[5] ? this.AS_RAW_MQ : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.AS_RAW_MQRankSum = fieldSetFlags()[6] ? this.AS_RAW_MQRankSum : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.AS_QUALapprox = fieldSetFlags()[7] ? this.AS_QUALapprox : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.AS_RAW_ReadPosRankSum = fieldSetFlags()[8] ? this.AS_RAW_ReadPosRankSum : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.AS_SB_TABLE = fieldSetFlags()[9] ? this.AS_SB_TABLE : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.AS_VarDP = fieldSetFlags()[10] ? this.AS_VarDP : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.call_GT = fieldSetFlags()[11] ? this.call_GT : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.call_AD = fieldSetFlags()[12] ? this.call_AD : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.call_DP = fieldSetFlags()[13] ? this.call_DP : (java.lang.Long) defaultValue(fields()[13]);
        record.call_GQ = fieldSetFlags()[14] ? this.call_GQ : (java.lang.Long) defaultValue(fields()[14]);
        record.call_PGT = fieldSetFlags()[15] ? this.call_PGT : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.call_PID = fieldSetFlags()[16] ? this.call_PID : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.call_PL = fieldSetFlags()[17] ? this.call_PL : (java.lang.CharSequence) defaultValue(fields()[17]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GenotypeRow>
    WRITER$ = (org.apache.avro.io.DatumWriter<GenotypeRow>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GenotypeRow>
    READER$ = (org.apache.avro.io.DatumReader<GenotypeRow>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.position == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.position);
    }

    if (this.sample == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.sample);
    }

    if (this.state == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.state);
    }

    if (this.ref == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.ref);
    }

    if (this.alt == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.alt);
    }

    if (this.AS_RAW_MQ == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.AS_RAW_MQ);
    }

    if (this.AS_RAW_MQRankSum == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.AS_RAW_MQRankSum);
    }

    if (this.AS_QUALapprox == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.AS_QUALapprox);
    }

    if (this.AS_RAW_ReadPosRankSum == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.AS_RAW_ReadPosRankSum);
    }

    if (this.AS_SB_TABLE == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.AS_SB_TABLE);
    }

    if (this.AS_VarDP == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.AS_VarDP);
    }

    if (this.call_GT == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.call_GT);
    }

    if (this.call_AD == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.call_AD);
    }

    if (this.call_DP == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.call_DP);
    }

    if (this.call_GQ == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.call_GQ);
    }

    if (this.call_PGT == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.call_PGT);
    }

    if (this.call_PID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.call_PID);
    }

    if (this.call_PL == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.call_PL);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.position = null;
      } else {
        this.position = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.sample = null;
      } else {
        this.sample = in.readString(this.sample instanceof Utf8 ? (Utf8)this.sample : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.state = null;
      } else {
        this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.ref = null;
      } else {
        this.ref = in.readString(this.ref instanceof Utf8 ? (Utf8)this.ref : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.alt = null;
      } else {
        this.alt = in.readString(this.alt instanceof Utf8 ? (Utf8)this.alt : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.AS_RAW_MQ = null;
      } else {
        this.AS_RAW_MQ = in.readString(this.AS_RAW_MQ instanceof Utf8 ? (Utf8)this.AS_RAW_MQ : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.AS_RAW_MQRankSum = null;
      } else {
        this.AS_RAW_MQRankSum = in.readString(this.AS_RAW_MQRankSum instanceof Utf8 ? (Utf8)this.AS_RAW_MQRankSum : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.AS_QUALapprox = null;
      } else {
        this.AS_QUALapprox = in.readString(this.AS_QUALapprox instanceof Utf8 ? (Utf8)this.AS_QUALapprox : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.AS_RAW_ReadPosRankSum = null;
      } else {
        this.AS_RAW_ReadPosRankSum = in.readString(this.AS_RAW_ReadPosRankSum instanceof Utf8 ? (Utf8)this.AS_RAW_ReadPosRankSum : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.AS_SB_TABLE = null;
      } else {
        this.AS_SB_TABLE = in.readString(this.AS_SB_TABLE instanceof Utf8 ? (Utf8)this.AS_SB_TABLE : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.AS_VarDP = null;
      } else {
        this.AS_VarDP = in.readString(this.AS_VarDP instanceof Utf8 ? (Utf8)this.AS_VarDP : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.call_GT = null;
      } else {
        this.call_GT = in.readString(this.call_GT instanceof Utf8 ? (Utf8)this.call_GT : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.call_AD = null;
      } else {
        this.call_AD = in.readString(this.call_AD instanceof Utf8 ? (Utf8)this.call_AD : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.call_DP = null;
      } else {
        this.call_DP = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.call_GQ = null;
      } else {
        this.call_GQ = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.call_PGT = null;
      } else {
        this.call_PGT = in.readString(this.call_PGT instanceof Utf8 ? (Utf8)this.call_PGT : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.call_PID = null;
      } else {
        this.call_PID = in.readString(this.call_PID instanceof Utf8 ? (Utf8)this.call_PID : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.call_PL = null;
      } else {
        this.call_PL = in.readString(this.call_PL instanceof Utf8 ? (Utf8)this.call_PL : null);
      }

    } else {
      for (int i = 0; i < 18; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.position = null;
          } else {
            this.position = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.sample = null;
          } else {
            this.sample = in.readString(this.sample instanceof Utf8 ? (Utf8)this.sample : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.state = null;
          } else {
            this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ref = null;
          } else {
            this.ref = in.readString(this.ref instanceof Utf8 ? (Utf8)this.ref : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.alt = null;
          } else {
            this.alt = in.readString(this.alt instanceof Utf8 ? (Utf8)this.alt : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.AS_RAW_MQ = null;
          } else {
            this.AS_RAW_MQ = in.readString(this.AS_RAW_MQ instanceof Utf8 ? (Utf8)this.AS_RAW_MQ : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.AS_RAW_MQRankSum = null;
          } else {
            this.AS_RAW_MQRankSum = in.readString(this.AS_RAW_MQRankSum instanceof Utf8 ? (Utf8)this.AS_RAW_MQRankSum : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.AS_QUALapprox = null;
          } else {
            this.AS_QUALapprox = in.readString(this.AS_QUALapprox instanceof Utf8 ? (Utf8)this.AS_QUALapprox : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.AS_RAW_ReadPosRankSum = null;
          } else {
            this.AS_RAW_ReadPosRankSum = in.readString(this.AS_RAW_ReadPosRankSum instanceof Utf8 ? (Utf8)this.AS_RAW_ReadPosRankSum : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.AS_SB_TABLE = null;
          } else {
            this.AS_SB_TABLE = in.readString(this.AS_SB_TABLE instanceof Utf8 ? (Utf8)this.AS_SB_TABLE : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.AS_VarDP = null;
          } else {
            this.AS_VarDP = in.readString(this.AS_VarDP instanceof Utf8 ? (Utf8)this.AS_VarDP : null);
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.call_GT = null;
          } else {
            this.call_GT = in.readString(this.call_GT instanceof Utf8 ? (Utf8)this.call_GT : null);
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.call_AD = null;
          } else {
            this.call_AD = in.readString(this.call_AD instanceof Utf8 ? (Utf8)this.call_AD : null);
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.call_DP = null;
          } else {
            this.call_DP = in.readLong();
          }
          break;

        case 14:
          if (in.readIndex() != 1) {
            in.readNull();
            this.call_GQ = null;
          } else {
            this.call_GQ = in.readLong();
          }
          break;

        case 15:
          if (in.readIndex() != 1) {
            in.readNull();
            this.call_PGT = null;
          } else {
            this.call_PGT = in.readString(this.call_PGT instanceof Utf8 ? (Utf8)this.call_PGT : null);
          }
          break;

        case 16:
          if (in.readIndex() != 1) {
            in.readNull();
            this.call_PID = null;
          } else {
            this.call_PID = in.readString(this.call_PID instanceof Utf8 ? (Utf8)this.call_PID : null);
          }
          break;

        case 17:
          if (in.readIndex() != 1) {
            in.readNull();
            this.call_PL = null;
          } else {
            this.call_PL = in.readString(this.call_PL instanceof Utf8 ? (Utf8)this.call_PL : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










