/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.broadinstitute.gatk.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MultiGenotypeGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 677273505876524954L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MultiGenotypeGroup\",\"namespace\":\"org.broadinstitute.gatk.avro\",\"fields\":[{\"name\":\"position\",\"type\":[\"null\",\"long\"]},{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"GenotypeSubRow\",\"fields\":[{\"name\":\"sample\",\"type\":[\"null\",\"string\"]},{\"name\":\"state\",\"type\":[\"null\",\"string\"]},{\"name\":\"ref\",\"type\":[\"null\",\"string\"]},{\"name\":\"alt\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_RAW_MQ\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_RAW_MQRankSum\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_QUALapprox\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_RAW_ReadPosRankSum\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_SB_TABLE\",\"type\":[\"null\",\"string\"]},{\"name\":\"AS_VarDP\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_GT\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_AD\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_DP\",\"type\":[\"null\",\"long\"]},{\"name\":\"call_GQ\",\"type\":[\"null\",\"long\"]},{\"name\":\"call_PGT\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_PID\",\"type\":[\"null\",\"string\"]},{\"name\":\"call_PL\",\"type\":[\"null\",\"string\"]}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MultiGenotypeGroup> ENCODER =
      new BinaryMessageEncoder<MultiGenotypeGroup>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MultiGenotypeGroup> DECODER =
      new BinaryMessageDecoder<MultiGenotypeGroup>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MultiGenotypeGroup> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MultiGenotypeGroup> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MultiGenotypeGroup> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MultiGenotypeGroup>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MultiGenotypeGroup to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MultiGenotypeGroup from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MultiGenotypeGroup instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MultiGenotypeGroup fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long position;
   private java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow> values;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MultiGenotypeGroup() {}

  /**
   * All-args constructor.
   * @param position The new value for position
   * @param values The new value for values
   */
  public MultiGenotypeGroup(java.lang.Long position, java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow> values) {
    this.position = position;
    this.values = values;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return position;
    case 1: return values;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: position = (java.lang.Long)value$; break;
    case 1: values = (java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'position' field.
   * @return The value of the 'position' field.
   */
  public java.lang.Long getPosition() {
    return position;
  }


  /**
   * Sets the value of the 'position' field.
   * @param value the value to set.
   */
  public void setPosition(java.lang.Long value) {
    this.position = value;
  }

  /**
   * Gets the value of the 'values' field.
   * @return The value of the 'values' field.
   */
  public java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow> getValues() {
    return values;
  }


  /**
   * Sets the value of the 'values' field.
   * @param value the value to set.
   */
  public void setValues(java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow> value) {
    this.values = value;
  }

  /**
   * Creates a new MultiGenotypeGroup RecordBuilder.
   * @return A new MultiGenotypeGroup RecordBuilder
   */
  public static org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder newBuilder() {
    return new org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder();
  }

  /**
   * Creates a new MultiGenotypeGroup RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MultiGenotypeGroup RecordBuilder
   */
  public static org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder newBuilder(org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder other) {
    if (other == null) {
      return new org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder();
    } else {
      return new org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder(other);
    }
  }

  /**
   * Creates a new MultiGenotypeGroup RecordBuilder by copying an existing MultiGenotypeGroup instance.
   * @param other The existing instance to copy.
   * @return A new MultiGenotypeGroup RecordBuilder
   */
  public static org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder newBuilder(org.broadinstitute.gatk.avro.MultiGenotypeGroup other) {
    if (other == null) {
      return new org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder();
    } else {
      return new org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder(other);
    }
  }

  /**
   * RecordBuilder for MultiGenotypeGroup instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MultiGenotypeGroup>
    implements org.apache.avro.data.RecordBuilder<MultiGenotypeGroup> {

    private java.lang.Long position;
    private java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow> values;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.position)) {
        this.position = data().deepCopy(fields()[0].schema(), other.position);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.values)) {
        this.values = data().deepCopy(fields()[1].schema(), other.values);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing MultiGenotypeGroup instance
     * @param other The existing instance to copy.
     */
    private Builder(org.broadinstitute.gatk.avro.MultiGenotypeGroup other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.position)) {
        this.position = data().deepCopy(fields()[0].schema(), other.position);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.values)) {
        this.values = data().deepCopy(fields()[1].schema(), other.values);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'position' field.
      * @return The value.
      */
    public java.lang.Long getPosition() {
      return position;
    }


    /**
      * Sets the value of the 'position' field.
      * @param value The value of 'position'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder setPosition(java.lang.Long value) {
      validate(fields()[0], value);
      this.position = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'position' field has been set.
      * @return True if the 'position' field has been set, false otherwise.
      */
    public boolean hasPosition() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'position' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder clearPosition() {
      position = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'values' field.
      * @return The value.
      */
    public java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow> getValues() {
      return values;
    }


    /**
      * Sets the value of the 'values' field.
      * @param value The value of 'values'.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder setValues(java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow> value) {
      validate(fields()[1], value);
      this.values = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'values' field has been set.
      * @return True if the 'values' field has been set, false otherwise.
      */
    public boolean hasValues() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'values' field.
      * @return This builder.
      */
    public org.broadinstitute.gatk.avro.MultiGenotypeGroup.Builder clearValues() {
      values = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MultiGenotypeGroup build() {
      try {
        MultiGenotypeGroup record = new MultiGenotypeGroup();
        record.position = fieldSetFlags()[0] ? this.position : (java.lang.Long) defaultValue(fields()[0]);
        record.values = fieldSetFlags()[1] ? this.values : (java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MultiGenotypeGroup>
    WRITER$ = (org.apache.avro.io.DatumWriter<MultiGenotypeGroup>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MultiGenotypeGroup>
    READER$ = (org.apache.avro.io.DatumReader<MultiGenotypeGroup>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.position == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.position);
    }

    long size0 = this.values.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (org.broadinstitute.gatk.avro.GenotypeSubRow e0: this.values) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.position = null;
      } else {
        this.position = in.readLong();
      }

      long size0 = in.readArrayStart();
      java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow> a0 = this.values;
      if (a0 == null) {
        a0 = new SpecificData.Array<org.broadinstitute.gatk.avro.GenotypeSubRow>((int)size0, SCHEMA$.getField("values").schema());
        this.values = a0;
      } else a0.clear();
      SpecificData.Array<org.broadinstitute.gatk.avro.GenotypeSubRow> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<org.broadinstitute.gatk.avro.GenotypeSubRow>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          org.broadinstitute.gatk.avro.GenotypeSubRow e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new org.broadinstitute.gatk.avro.GenotypeSubRow();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.position = null;
          } else {
            this.position = in.readLong();
          }
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<org.broadinstitute.gatk.avro.GenotypeSubRow> a0 = this.values;
          if (a0 == null) {
            a0 = new SpecificData.Array<org.broadinstitute.gatk.avro.GenotypeSubRow>((int)size0, SCHEMA$.getField("values").schema());
            this.values = a0;
          } else a0.clear();
          SpecificData.Array<org.broadinstitute.gatk.avro.GenotypeSubRow> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<org.broadinstitute.gatk.avro.GenotypeSubRow>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              org.broadinstitute.gatk.avro.GenotypeSubRow e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new org.broadinstitute.gatk.avro.GenotypeSubRow();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










